# -*- coding: utf-8 -*-
"""
/***************************************************************************
SavetoPostGIS
                                 A QGIS plugin
 This plugin is for upload data to PostgreSQL database from layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-24
        copyright            : (C) 2023 by BIG - UNGEGN
        email                : nna-ina@big.go.id
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SavetoPostGIS class from file SavetoPostGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .save_to_postgis import SavetoPostGIS
    return SavetoPostGIS(iface)
